name: Route Changes Check

on:
  pull_request:
    branches:
      - dev
      - master
      - main

jobs:
  check-routes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run check for router changes
      id: check-routes
      run: |
        # Run the shell script and capture the result
        ./check_router_changes.sh
        echo "router_changes_detected=$?" >> $GITHUB_ENV

    - name: Add comment if route changes detected
      if: env.router_changes_detected == '0'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = context.payload.pull_request.number;
          const commentBody = `
            ## Route Changes Detected
            This pull request includes changes to the \`/routes\` folder. Please review and confirm these changes.
            - **Status:** Review required
          `;
          await github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: commentBody
          });

    - name: Set PR status to review required
      if: env.router_changes_detected == '0'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = context.payload.pull_request.number;
          await github.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'failure',
            target_url: '',
            description: 'Route changes detected, review required',
            context: 'Route Changes Check'
          });

    - name: No route changes detected
      if: env.router_changes_detected != '0'
      run: echo "No route changes detected, PR can proceed."