name: Services Pipeline

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'my-express-app/services/**/routes/**'
      - '!my-express-app/services/**/lambda/**'

jobs:
  check-router-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Fetch all branches
      run: git fetch --all

    - name: Run check for router changes
      run: |
        chmod +x check_router_changes.sh
        ./check_router_changes.sh
        
    - name: Continue only if router changes are detected
      if: success()
      run: |
        echo "Router changes detected. Proceeding with the pipeline."
        cd my-express-app
        npm install